# -- Site Configuration --

# URL to the root of your website.
baseURL = 'https://mnjm.github.io/kayal'

# Site's language code
languageCode = 'en-us'

title = "Kayal"

theme = "kayal" # UNCOMMENT THIS LINE

# Number of articles per page in the listing.
[pagination]
  pagerSize = 5

# Enable processing of emojis in markdown.
enableEmoji = true

# Enable creation of robots.txt for search engine crawling.
enableRobotsTXT = true

# Length of default summaries.
summaryLength = 0

# Build drafts during site generation.
buildDrafts = true
# Build pages with future dates during site generation.
buildFuture = true

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# The types of outputs to generate for the homepage.
# RSS is required to create RSS feeds, and JSON is needed for the search to function.
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Google Analytics Configuration
# [services]
#   [services.googleAnalytics]
#     ID = 'G-MEASUREMENT_ID'
